export const CHANGE_MSG = 'CHANGE_MSG';
export const CHANGE_ARTICLES = 'CHANGE_ARTICLES';
export const GET_DATA_SA_ACTION = 'GET_DATA_SA_ACTION';
export const DELETE_DATA_SA_ACTION = 'DELETE_DATA_SA_ACTION';
